fix: add missing `__all__` in init file
Without it the user will see the following error:
```
2025-04-10 12:13:29,627 - ERROR - fast_api.py:616 - Error in event_generator: module 'multi_tool_agent.agent' has no attribute 'root_agent'
Traceback (most recent call last):
  File "/Users/sroze/git/adk-agent-test/.venv/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 604, in event_generator
    runner = _get_runner(req.app_name)
  File "/Users/sroze/git/adk-agent-test/.venv/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 756, in _get_runner
    root_agent = _get_root_agent(app_name)
  File "/Users/sroze/git/adk-agent-test/.venv/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 748, in _get_root_agent
    root_agent: Agent = agent_module.agent.root_agent
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```